name: Add character
description: add new Genshin Impact character to database
body:
- type: dropdown
  id: element
  attributes:
    label: Element
    options:
    - Pyro
    - Hydro
    - Electro
    - Anemo
    - Dendro
    - Geo
    - Cryo
  validations:
    required: true
