name: "Nová postava"
description: "Formulář pro přidání nové postavy do databáze"
body:
  - type: markdown
    attributes:
      value: |
        Děkujeme za zájem o rozšíření **GBDB**! Prosím, vyplňte pole níže. [cite: 7]
  - type: input
    id: char_id
    attributes:
      label: "ID postavy"
      placeholder: "např. raiden-shogun"
    validations:
      required: true
  - type: dropdown
    id: element
    attributes:
      label: "Element"
      options:
        - Pyro
        - Hydro
        - Electro
        - Anemo
        - Dendro
        - Geo
        - [cite_start]Cryo [cite: 14]
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Popis talentů"
      [cite_start]placeholder: "Popište, co talent dělá..." [cite: 20]
